---
output:
  pdf_document: default
  html_document: default
---

# 9.6.4 SVM with Multiple Classes

## Set up Support Vector Machine


*   Factor the data frame
*   Create a train set

```{r message=FALSE}
library(e1071)
set.seed(1)
x=matrix(rnorm(200*2), ncol=2)
x[1:100,]=x[1:100,]+2
x[101:150,]=x[101:150,]-2
y=c(rep(1,150),rep(2,50))
dat=data.frame(x=x,y=as.factor(y))
train=sample(200,100)
```



This is where 9.6.4 really starts, but you need the other inputs to run the following code. 

If the response is a factor containing more than two levels, then the svm() function will perform multi-class classiﬁcation using the one-versus-one approach. 

```{r}
set.seed(1)
x=rbind(x, matrix(rnorm(50*2), ncol=2))
y=c(y, rep(0,50))
x[y==0,2]=x[y==0,2]+2
dat=data.frame(x=x, y=as.factor(y))
par(mfrow=c(1,1))
plot(x,col=(y+1))

```
We now ﬁt an SVM to the data:

```{r}
svmfit=svm(y~., data=dat, kernel="radial", cost=10, gamma=1)
plot(svmfit, dat)
```

